In [9]:
import sys
from datetime import datetime
sys.path.append('../src/')
from read_jleague_matches import read_all_matches, update_all_matches, read_matches_range

In [10]:
CATEGORY = 3

all_matches = read_all_matches(CATEGORY)
# all_matches.to_csv(f'match_result-J{CATEGORY}-{datetime.now().strftime("%Y%m%d")}.csv')

all_matches

,match_date,section_no,match_index_in_section,start_time,stadium,home_team,home_goal,away_goal,away_team
0,2021-03-14,1,1,13:03,とうスタ,藤枝,0,0,福島
1,2021-03-14,1,2,13:03,ニッパツ,富山,1,0,YS横浜
2,2021-03-14,1,3,13:03,夢スタ,熊本,1,0,今治
3,2021-03-14,1,4,13:03,ユニスタ,岩手,1,0,宮崎
4,2021-03-14,1,5,14:03,長良川,八戸,0,0,岐阜
...,...,...,...,...,...,...,...,...,...
2,2021-11-28,29,3,未定,長良川,藤枝,,,岐阜
3,2021-11-28,29,4,未定,夢スタ,八戸,,,今治
4,2021-11-28,29,5,未定,白波スタ,長野,,,鹿児島
5,2021-11-28,29,6,未定,ユニスタ,熊本,,,宮崎
6,NaT,29,7,未定,未定,鳥取,,,讃岐

In [11]:
sec30 = read_matches_range(3, [30])
sec30

,match_date,section_no,match_index_in_section,start_time,stadium,home_team,home_goal,away_goal,away_team
0,2021-12-05,30,1,未定,とうスタ,讃岐,,,福島
1,2021-12-05,30,2,未定,長野Ｕ,今治,,,長野
2,2021-12-05,30,3,未定,富山,鹿児島,,,富山
3,2021-12-05,30,4,未定,藤枝サ,YS横浜,,,藤枝
4,2021-12-05,30,5,未定,愛鷹,岩手,,,沼津
5,2021-12-05,30,6,未定,Ａｘｉｓ,八戸,,,鳥取
6,2021-12-05,30,7,未定,えがおＳ,岐阜,,,熊本

In [12]:
all_matches[all_matches['section_no'] == 30]

Empty DataFrame
Columns: [match_date, section_no, match_index_in_section, start_time, stadium, home_team, home_goal, away_goal, away_team]
Index: []

In [4]:
current_matches = update_all_matches(1)
#diff_matches = read_matches_range(1, need_update)

match file "../csv/match_result-J1-20210528.csv" reading.

In [5]:
current_matches

,index,match_date,section_no,match_index_in_section,start_time,stadium,home_team,home_goal,away_goal,away_team
0,0,2021-02-26,1,1,18:04,等々力,横浜FM,0,2,川崎Ｆ
1,1,2021-02-27,1,2,14:00,札幌ド,横浜FC,1,5,札幌
2,2,2021-02-27,1,3,14:00,埼玉,FC東京,1,1,浦和
3,3,2021-02-27,1,4,14:03,Ｅスタ,仙台,1,1,広島
4,4,2021-02-27,1,5,14:03,昭和電ド,徳島,1,1,大分
...,...,...,...,...,...,...,...,...,...,...
375,5,2021-05-30,17,6,15:04,鳴門大塚,湘南,1,1,徳島
376,6,2021-05-30,17,7,15:03,昭和電ド,福岡,1,2,大分
377,7,2021-05-30,17,8,17:03,パナスタ,横浜FC,0,2,Ｇ大阪
378,8,2021-05-30,17,9,18:04,埼玉,名古屋,0,0,浦和
379,9,2021-05-30,17,10,19:01,等々力,鹿島,1,2,川崎Ｆ